In [3]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [4]:
arr2 = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr2[0:8:1])

[1 2 3 4 5 6 7 8]


In [5]:
arr3 = np.zeros(5, dtype = int)
print(arr3)

[0 0 0 0 0]


In [6]:
arr4 = np.ones(5, dtype = int)
print(arr4)

[1 1 1 1 1]


In [7]:
identity_mtrx = np.eye((2))
print(identity_mtrx)

[[1. 0.]
 [0. 1.]]


In [42]:
#Array with values from 1-20 :- (1st way)
arr = np.array([], dtype = int)
for i in range(1, 21):
    arr = np.append(arr, i)

print(arr)

#(Using arange() method) :-
arr = np.arange(1,21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [34]:
temp = np.array([], dtype = int)
#Finding the Prime No's :-
for i in range(len(arr)):
    if i < 2: continue
    flag = True
    for j in range(2, int(i**0.5) + 1):
        if i % j == 0:
            flag = False
            break
    if flag:
        temp = np.append(temp, i)

#Calc Mean:-
sum = 0
for i in range(len(temp)):
    sum += temp[i]

mean = sum / len(temp)
print(mean)
#Calc Variance :-
variance = np.var(temp)
print(variance)

9.625
35.734375


In [46]:
arr = np.arange(1,17).reshape(4,4)
print(arr)
print("\n")
sub_mtrx = arr[2:4 , 0:2]
print(sub_mtrx)
det = np.linalg.det(sub_mtrx)
print(det)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


[[ 9 10]
 [13 14]]
-4.000000000000009
