In [9]:
#Q1 :-
import numpy as np
arr = np.arange(1,21)
primes = []
for i in arr:
    if i > 1:
        flag = True
    for j in range(2,int(i**0.5) + 1):
        if i % j == 0:
            flag = False
            break
    if flag:
        primes.append(int(i))

mean = np.mean(primes)
var = np.var(primes)
print(arr)
print(primes)
print(mean)
print(var)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[2, 3, 5, 7, 11, 13, 17, 19]
9.625
35.734375


In [15]:
# Q2
arr = np.arange(1,17).reshape(4,4)
sub = arr[2:, :2]
det = np.linalg.det(sub)
print(sub)
print(det)

[[ 9 10]
 [13 14]]
-4.000000000000009


In [26]:
# Q3
import pandas as pd

df = pd.DataFrame(
    {'Name': ['Pratik', 'Ankush', 'Aditya', 'Debasish', 'Prasanjit'],
        'Math': [90,95,70,85,80],
        'Sci': [95,100,80,90,85],
        'Eng':[80,70,80,70,80],
    })

df['Total'] = df[['Math','Sci','Eng']].sum(axis=1)
df['Average'] = df['Total'] / 3
print(df)

        Name  Math  Sci  Eng  Total    Average
0     Pratik    90   95   80    265  88.333333
1     Ankush    95  100   70    265  88.333333
2     Aditya    70   80   80    230  76.666667
3   Debasish    85   90   70    245  81.666667
4  Prasanjit    80   85   80    245  81.666667


In [33]:
# Q5
import pandas as pd
df = pd.DataFrame(
    {'ID': [1,2,3],
     'Name': ['Pratik', 'Aditya', 'Ankush'],
     'Salary': [1000,1500,800]
})

df['Bonus'] = df['Salary']*0.1
avg = df['Salary'].mean()
print
print(df)

   ID    Name  Salary  Bonus
0   1  Pratik    1000  100.0
1   2  Aditya    1500  150.0
2   3  Ankush     800   80.0


In [45]:
# Q6
import numpy as np
arr = np.arange(1,10).reshape(3,3)
arr_transp = arr.T
arr_inv = np.linalg.inv(arr)
verify = np.dot(arr, arr_inv)
print("\nTranspose of A:\n: ",arr_transp)
print("\nInverse of A:\n: ", arr_inv)
print(I)

LinAlgError: Singular matrix

In [47]:
# Q7
temp = np.random.uniform(20,40,30)
print("Hottest Day: ", temp.max())
print("Coldest Day: ", temp.min())
print("Mean: ", np.mean(temp))
print("Median: ", np.median(temp))
print("Standard Deviation: ", np.std(temp))

Hottest Day:  39.42881912249339
Coldest Day:  20.486368619582386
Mean:  32.26055122541945
Median:  33.29148120093972
Standard Deviation:  4.7580557813624464


In [49]:
# Q8
import pandas as pd
marks = pd.Series([35,55,70,20,80,60,30,90])
marks = marks.where(marks >= 40, "Fail")
print("Passed: ",(marks != "Fail").sum())

Passed:  5


In [51]:
# Q9
random_num = np.random.randint(1,7,500)
random_num


array([2, 1, 3, 1, 4, 3, 5, 2, 2, 3, 1, 2, 2, 3, 4, 3, 1, 4, 2, 2, 2, 2,
       1, 4, 5, 6, 1, 4, 4, 4, 2, 6, 6, 2, 2, 5, 4, 6, 5, 4, 5, 6, 2, 2,
       6, 2, 2, 5, 3, 5, 5, 2, 6, 6, 6, 4, 4, 4, 5, 4, 4, 6, 1, 2, 3, 1,
       5, 1, 2, 2, 6, 5, 1, 4, 6, 2, 6, 2, 2, 6, 3, 6, 5, 5, 4, 2, 3, 4,
       1, 6, 5, 5, 3, 4, 5, 1, 3, 3, 2, 1, 2, 3, 3, 4, 6, 4, 4, 5, 2, 2,
       5, 3, 4, 3, 2, 4, 6, 2, 6, 2, 1, 2, 2, 4, 2, 4, 3, 2, 4, 5, 3, 5,
       4, 1, 2, 2, 2, 1, 5, 3, 3, 4, 3, 2, 2, 4, 5, 4, 1, 5, 2, 4, 1, 5,
       6, 5, 3, 5, 4, 5, 6, 3, 5, 5, 3, 4, 5, 3, 4, 1, 3, 4, 6, 4, 1, 1,
       5, 4, 2, 4, 5, 1, 2, 2, 3, 4, 4, 5, 3, 4, 6, 4, 2, 5, 1, 3, 5, 4,
       6, 3, 4, 5, 6, 6, 6, 1, 3, 2, 3, 2, 4, 2, 1, 5, 2, 1, 6, 4, 5, 6,
       1, 6, 2, 4, 4, 2, 3, 4, 2, 2, 5, 3, 4, 3, 1, 5, 4, 1, 4, 5, 2, 4,
       6, 1, 5, 4, 4, 2, 3, 3, 2, 4, 5, 5, 1, 2, 2, 3, 5, 6, 2, 4, 6, 5,
       5, 1, 1, 6, 1, 1, 5, 2, 5, 1, 1, 5, 5, 5, 5, 4, 6, 4, 3, 1, 6, 1,
       1, 1, 4, 4, 3, 6, 4, 3, 2, 3, 4, 5, 1, 1, 5,

In [65]:
# Q10
data = pd.DataFrame({
    'Name': ['AC', 'Fan', 'Ceiling Lights', 'Inchi Tape','Screws and nuts'],
    'Quantity': [2,4,10,2,200],
    'Price': [100,200,300,400,500]
    })

data['Total'] = data['Quantity'] * data['Price']
print(data,"\n")
max_prod = data.loc[data['Total'].idxmax()]
print("Maximum sales revenue: ",max_prod['Name'])

              Name  Quantity  Price   Total
0               AC         2    100     200
1              Fan         4    200     800
2   Ceiling Lights        10    300    3000
3       Inchi Tape         2    400     800
4  Screws and nuts       200    500  100000 

Maximum sales revenue:  Screws and nuts


In [72]:
# Q12
import numpy as np
arr = np.arange(1,31).reshape(5,6)
even = arr[arr%2==0]
print(even)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]


In [84]:
import pandas as pd
df = pd.DataFrame({
    'Name': ['pratik','ankush','aditya','debasish','prasanjit','saurav'],
    'Age': [20,19,18,20,23,21],
    'Marks': [90,80,90,80,70,60]
})
avg = df['Marks'].mean()
print(df,"\n")
print(avg)

print("Above avg:\n", df[df['Marks']>avg])
shortlisting = df[(df['Age'] < 20) & (df['Marks'] > 60)]
print("\n",shortlisting['Name'])

        Name  Age  Marks
0     pratik   20     90
1     ankush   19     80
2     aditya   18     90
3   debasish   20     80
4  prasanjit   23     70
5     saurav   21     60 

78.33333333333333
Above avg:
        Name  Age  Marks
0    pratik   20     90
1    ankush   19     80
2    aditya   18     90
3  debasish   20     80

 1    ankush
2    aditya
Name: Name, dtype: object


In [81]:
df = pd.DataFrame({
    'Name':['A','B','C','D','E','F'],
    'Age':[18,22,19,21,20,17],
    'Marks':[55,65,70,60,80,40]
})
avg = df['Marks'].mean()
print("Above avg:\n", df[df['Marks']>avg])
print("Under 20 & >60:\n", df[(df['Age']<20)&(df['Marks']>60)])

Above avg:
   Name  Age  Marks
1    B   22     65
2    C   19     70
4    E   20     80
Under 20 & >60:
   Name  Age  Marks
2    C   19     70
