In [2]:
import numpy as np
a = np.ones((2,3))
b = np.zeros((3,3))
c = np.full((2,5),7)
print(a)
print(b)
print(c)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[7 7 7 7 7]
 [7 7 7 7 7]]


In [5]:
arr = np.arange(4).reshape(2,2)
b = arr ** 3
c = arr + 7
d = arr * 2 
print(b)
print(c)
print(d)

[[ 0  1]
 [ 8 27]]
[[ 7  8]
 [ 9 10]]
[[0 2]
 [4 6]]


In [7]:
a = np.arange(2,20,2).reshape(3,3)
b = np.arange(9,0,-1).reshape(3,3)
c = a * b
print(c)

[[18 32 42]
 [48 50 48]
 [42 32 18]]


In [13]:
a = np.arange(9).reshape(3,3)
print(a)
a[[0,1]] = a[[1,0]]
print("first 2 rows swapped: \n",a)

a[:,[0,1]] = a[:,[1,0]]
print("First 2 cols swapped: \n",a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
first 2 rows swapped: 
 [[3 4 5]
 [0 1 2]
 [6 7 8]]
First 2 cols swapped: 
 [[4 3 5]
 [1 0 2]
 [7 6 8]]


In [15]:
lst = [[2,3,5,7,11],[13,17,19,23,29]]
a = np.array(lst)
print(a)

[[ 2  3  5  7 11]
 [13 17 19 23 29]]


In [26]:
lst = [2**i for i in range(6)]
arr = np.reshape(lst, (2,3))
print(arr)
f = arr.flatten()
print("FLATTEN: \nflattened arr :\n",f)
f[0] = 100
print("after modification :\n",f)
print("orginal arr after mod: \n",arr)

r = arr.ravel()
print("\nRAVEL: \nraveled arr :\n",r)
r[0] = 100
print("after modification :\n",r)
print("orginal arr after mod: \n",arr)

[[ 1  2  4]
 [ 8 16 32]]
FLATTEN: 
flattened arr :
 [ 1  2  4  8 16 32]
after modification :
 [100   2   4   8  16  32]
orginal arr after mod: 
 [[ 1  2  4]
 [ 8 16 32]]

RAVEL: 
raveled arr :
 [ 1  2  4  8 16 32]
after modification :
 [100   2   4   8  16  32]
orginal arr after mod: 
 [[100   2   4]
 [  8  16  32]]


In [27]:
arr = np.array([6,9,5,1,7,5,1,0,1,5,5,0,8,9,0,7,0,7,6,5,1,1,9,5,3,8,7,9,6,3,4,5,9,7,2,7,0,2,2,6])

values, counts = np.unique(arr, return_counts=True)
most_frequent = np.argmax(counts)
print(values[most_frequent])

5


In [32]:
arr = np.linspace(1.1,6.6,6).reshape(2,3)
print(arr)
arr_int = arr.astype(int)
print(arr_int)

[[1.1 2.2 3.3]
 [4.4 5.5 6.6]]
[[1 2 3]
 [4 5 6]]


In [40]:
# Q10
arr = np.arange(1,16).reshape(3,5)
print(arr)

row2 = arr[1]
print("2nd row :\n",row2)

col5 = arr[:,4]
print("5th col: \n",col5)

row01 = arr[0:2]
print(row01)

col2_4 = arr[:,2:5]
print(col2_4)

r1c4 = arr[1,4]
print(r1c4)

ele = arr[1:3][:,[0,2,4]]
print(ele)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
2nd row :
 [ 6  7  8  9 10]
5th col: 
 [ 5 10 15]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]
10
[[ 6  8 10]
 [11 13 15]]


In [45]:
arr1 = np.array([[0,1], [2,3]])
arr2 = np.array([[4,5], [6,7]])

arr3 = np.vstack((arr1,arr2))
print(arr3)

arr4 = np.hstack((arr1,arr2))
print(arr4)

arr5 = np.vstack((arr4,arr4))
print(arr5)

arr6 = np.hstack((arr3,arr3))
print(arr6)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 1 4 5]
 [2 3 6 7]]
[[0 1 4 5]
 [2 3 6 7]
 [0 1 4 5]
 [2 3 6 7]]
[[0 1 0 1]
 [2 3 2 3]
 [4 5 4 5]
 [6 7 6 7]]


In [3]:
# QUESTION-12
arr1 = np.array([[0,1], [2,3]])
arr2 = np.array([[4,5], [6,7]])

arr3 = np.concatenate((arr1,arr2),axis=0)
arr4 = np.concatenate((arr1,arr2),axis=1)
arr5 = np.concatenate((arr4,arr4),axis=0)
arr6=  np.concatenate((arr3,arr3),axis=1)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [5]:
# QUESTION-13
arr = np.array([['-','*'],['*','-']])
pattern = np.tile(arr,(4,4))
print(pattern)

[['-' '*' '-' '*' '-' '*' '-' '*']
 ['*' '-' '*' '-' '*' '-' '*' '-']
 ['-' '*' '-' '*' '-' '*' '-' '*']
 ['*' '-' '*' '-' '*' '-' '*' '-']
 ['-' '*' '-' '*' '-' '*' '-' '*']
 ['*' '-' '*' '-' '*' '-' '*' '-']
 ['-' '*' '-' '*' '-' '*' '-' '*']
 ['*' '-' '*' '-' '*' '-' '*' '-']]


In [9]:
# Q14
random = np.random.randint(0,100,(5,5))
print(random)

[[33 74 13 52 13]
 [98 82 20  4 27]
 [ 1 57 20 41 92]
 [63 38 25 86 29]
 [17 44 13 84 15]]


In [12]:
file_path = r'C:\MyFolder\MySubFolder\MyFile.txt'
file_path

'C:\\MyFolder\\MySubFolder\\MyFile.txt'